import json
from groq import Groq

from tools.inquiry_parser import parse_inquiry
from tools.mls_matcher    import match_listings
from tools.lead_analyst   import analyse_lead


# ── Final Brief ka template ────────────────────────────────────────────────────
# LLM ko exactly yeh format follow karna hai
BRIEF_SYSTEM_PROMPT = """You are writing a Lead Brief for a busy real estate agent.
They will read this before calling the buyer. Make it scannable.

Write in clean Markdown. Follow this exact structure:

# Lead Brief — {buyer_name}
**Received:** {date} via {channel}
**Contact:** {phone} | {email}
**Urgency:** (use 🔴 Hot or 🟡 Warm or 🟢 Cold)

---

## What They're Looking For
2-3 sentences about buyer's situation and goals in plain English.

## Budget & Requirements
- **Budget:** $X – $Y
- **Bedrooms:** X+
- **Neighborhoods:** ...
- **Must-haves:** ...
- **Nice-to-haves:** ...
- **Timeline:** ...
- **Buyer type:** ...

## Top Matching Properties
### 1. [Address] — $[Price]
- **Why it fits:** ...
- **Watch out:** ...

(repeat for each match, max 5)

## Before You Call
- bullet points of concerns or context

## Suggested Next Action
**[Action]:** One specific sentence.

## Qualifying Questions to Ask
1. ...
2. ...
3. ...

---
*Brief generated by AgentMira Buyer Lead Intake Agent*"""


def run_agent(client: Groq, csv_path: str, lead: dict) -> dict:
    """
    Ek buyer lead ke liye poora agent pipeline chalao.
    
    Input:  lead dict (JSON file se ek entry)
    Output: dict jisme brief_markdown aur saara intermediate data hai
    """

    # Lead se basic info nikalo
    lead_id      = lead.get("lead_id", "UNKNOWN")
    buyer_name   = lead.get("buyer_name", "Anonymous")
    buyer_email  = lead.get("buyer_email", "")
    buyer_phone  = lead.get("buyer_phone", "")
    channel      = lead.get("channel", "unknown")
    received_at  = lead.get("received_at", "")
    message      = lead.get("message", "")

    print(f"\n{'='*55}")
    print(f"  Processing {lead_id} — {buyer_name}")
    print(f"{'='*55}")

    # ── Step 1: Inquiry Parser ─────────────────────────────────
    print("  [1/4] Parsing inquiry...")

    requirements = parse_inquiry(client, buyer_name, message)

    bmin = requirements.get('budget_min') or 0
    bmax = requirements.get('budget_max') or 0
    print(f"  ✓ Budget: ${bmin:,.0f}–${bmax:,.0f} | "
          f"Beds: {requirements.get('bedrooms_min', '?')}+ | "
          f"Quality: {requirements.get('lead_quality', '?')}/5")

    # ── Step 2: MLS Matcher ────────────────────────────────────
    # requirements yahan directly pass ho raha hai inquiry_parser se
    print("  [2/4] Matching MLS listings...")

    matches = match_listings(client, csv_path, requirements, buyer_name)

    print(f"  ✓ {len(matches.get('matches', []))} matches found "
          f"({matches.get('total_after_filter', '?')} after hard filter)")

    # ── Step 3: Lead Analyst ───────────────────────────────────
    # requirements + matches dono pass ho rahe hain
    print("  [3/4] Analysing lead...")

    analysis = analyse_lead(
        client           = client,
        buyer_name       = buyer_name,
        buyer_email      = buyer_email,
        buyer_phone      = buyer_phone,
        channel          = channel,
        received_at      = received_at,
        original_message = message,
        requirements     = requirements,   # ← Step 1 ka output
        matches          = matches         # ← Step 2 ka output
    )

    print(f"  ✓ Urgency: {analysis.get('urgency', '?').upper()} | "
          f"Action: {analysis.get('suggested_next_action', '')[:50]}...")

    # ── Step 4: Final Brief Synthesis ─────────────────────────
    # Teeno tools ka output ek saath LLM ko do
    print("  [4/4] Generating Lead Brief...")

    # Contact info ek string mein banao
    contact_parts = []
    if buyer_phone: contact_parts.append(buyer_phone)
    if buyer_email: contact_parts.append(buyer_email)
    contact_info = " | ".join(contact_parts) or "No contact info"

    # Urgency ke hisaab se emoji
    urgency_emoji = {
        "hot":  "🔴",
        "warm": "🟡",
        "cold": "🟢"
    }.get(analysis.get("urgency", "warm"), "🟡")

    # Teeno tools ka output ek prompt mein combine karo
    synthesis_prompt = f"""Write the Lead Brief using this data:

BUYER INFO:
- Name: {buyer_name}
- Contact: {contact_info}
- Channel: {channel}
- Received: {received_at}
- Urgency: {urgency_emoji} {analysis.get('urgency', 'warm').title()}
- Original message: "{message[:300]}"

PARSED REQUIREMENTS:
{json.dumps(requirements, indent=2)}

MLS MATCHES:
{json.dumps(matches, indent=2)}

LEAD ANALYSIS:
{json.dumps(analysis, indent=2)}

Write the complete Lead Brief now. Use the exact Markdown format from your instructions."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": BRIEF_SYSTEM_PROMPT},
            {"role": "user",   "content": synthesis_prompt}
        ],
        temperature=0.4,
        max_tokens=2000
    )

    brief_markdown = response.choices[0].message.content.strip()
    print(f"  ✓ Brief generated ({len(brief_markdown)} chars)")

    # ── Sab kuch return karo ───────────────────────────────────
    return {
        "lead_id":        lead_id,
        "buyer_name":     buyer_name,
        "brief_markdown": brief_markdown,   # ← Final output
        "requirements":   requirements,     # ← Step 1 ka output (debug ke liye)
        "matches":        matches,          # ← Step 2 ka output (debug ke liye)
        "analysis":       analysis,         # ← Step 3 ka output (debug ke liye)
        "status":         "success"
    }